---
# Device Discovery and Fabric Configuration
# Variables for discovery, LAN automation, and provisioning roles
discovery_details:
  - ip_address_list:
    - 204.192.12.1-204.192.12.1
    - 204.192.13.1-204.192.13.1
    discovery_type: MULTI RANGE
    protocol_order: ssh
    discovery_name: Multi Range Discoveryfor WLCs
    global_credentials:
      cli_credentials_list:
      - description: switchandwlc credentials
        username: wlcaccess
      snmp_v3_credential_list:
      - description: snmpV3 Sample 1
        username: admin
      http_read_credential_list:
      - username: admin
        description: httpsRead Sample 1
      http_write_credential_list:
      - username: admin
        description: httpsWrite Sample 1
    discovery_specific_credentials:
      net_conf_port: '830'
    timeout: 30
    retry: 2
  - ip_address_list:
    - 204.101.16.1-204.101.16.2
    - 204.101.16.4-204.101.16.14
    discovery_type: MULTI RANGE
    protocol_order: ssh
    discovery_name: Multi Range Discoveryfor switches
    global_credentials:
      cli_credentials_list:
      - description: switchandwlc credentials
        username: wlcaccess
      snmp_v3_credential_list:
      - description: snmpV3 Sample 1
        username: admin
      http_read_credential_list:
      - username: admin
        description: httpsRead Sample 1
      http_write_credential_list:
      - username: admin
        description: httpsWrite Sample 1
    discovery_specific_credentials:
      net_conf_port: '830'
    timeout: 30
    retry: 2
  - ip_address_list:
    - 204.192.3.40
    discovery_type: SINGLE
    protocol_order: ssh
    discovery_name: Fusion Router
    global_credentials:
      cli_credentials_list:
      - description: switchandwlc credentials
        username: wlcaccess
      snmp_v3_credential_list:
      - description: snmpV3 Sample 1
        username: admin
      http_read_credential_list:
      - username: admin
        description: httpsRead Sample 1
      http_write_credential_list:
      - username: admin
        description: httpsWrite Sample 1
    discovery_specific_credentials:
      net_conf_port: '830'
    timeout: 30
    retry: 2
