---
# Master BGP EVPN Deployment Playbook
# This playbook orchestrates the complete EVPN fabric deployment using Catalyst Center
# 
# Execution Order:
# 1. ISE Integration
# 2. Site Hierarchy Design
# 3. Global Credentials
# 4. Device Discovery
# 5. Site Assignment
# 6. LAN Automation
# 7. Device Provisioning
# 8. Template Creation & Deployment
# 9. Validation

- name: "BGP EVPN Fabric Deployment - Complete Workflow"
  hosts: catalyst_center
  connection: local
  gather_facts: false
  #vars_files:
  #  - ../vars/global.yml
  #  - ../data/bgp_evpn_site_01.yml
  
  tasks:
    - name: "Display deployment banner"
      debug:
        msg: |
          ================================================================================
          Starting BGP EVPN Fabric Deployment
          ================================================================================
          Sites to be deployed: {{ sites | map(attribute='site_name') | list | join(', ') }}
          Catalyst Center: {{ catalyst_center_host }}
          ================================================================================

    # Phase 1: ISE Integration
    - name: "Phase 1: Configure ISE Integration"
      include_role:
        name: catalyst_center_ise_aaa_integration
      tags: ['ise']

    # Phase 2: Site Hierarchy Design  
    - name: "Phase 2: Create Site Hierarchy"
      include_role:
        name: catalyst_center_site_design
      tags: ['sites']

    # # Phase 3: Global Credentials
    - name: "Phase 3: Configure Global Credentials"
      include_role:
        name: catalyst_center_device_credentials
      tags: ['credentials']

    # Phase 4: Network Settings
    - name: "Phase 4: Configure Network Settings"
      include_role:
        name: catalyst_center_network_settings
      tags: ['network']

    # Phase 5: IP Pool Management
    - name: "Phase 5: Configure IP Pools"
      include_role:
        name: catalyst_center_network_settings
      tags: ['ippools']

    # Phase 6: Device Discovery
    - name: "Phase 6: Discover Seed Devices"
      include_role:
        name: catalyst_center_device_discovery
      tags: ['discovery']

    # Phase 7: Site Assignment
    - name: "Phase 7: Assign Devices to Sites"
      include_role:
        name: catalyst_center_device_provision
      tags: ['assignment']

    # Phase 8: LAN Automation
    - name: "Phase 8: Execute LAN Automation"
      include_role:
        name: catalyst_center_lan_automation
      tags: ['lanautomation']

    # Phase 9: Device Provisioning
    - name: "Phase 9: Provision All Devices"
      include_role:
        name: catalyst_center_device_provision
      tags: ['provision']

    # Phase 10: Template Creation
    - name: "Phase 10: Create EVPN Templates"
      include_role:
        name: catalyst_center_template_creation
      tags: ['templates']

    # Phase 11: Template Deployment
    - name: "Phase 11: Deploy Templates to Devices"
      include_role:
        name: catalyst_center_template_deployment
      tags: ['deploy']

    # Phase 12: Validation
    - name: "Phase 12: Validate EVPN Underlay and Overlay"
      include_role:
        name: catalyst_center_evpn_validation
      tags: ['validate']

    - name: "Display deployment completion banner"
      debug:
        msg: |
          ================================================================================
          BGP EVPN Fabric Deployment Completed Successfully!
          ================================================================================
          All phases completed. Run validation playbook to verify the deployment.
          ================================================================================